Vidly/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vidly.Controllers
{
    public class RentalsController : Controller
    {
        // GET: Rentals
        public ActionResult New()
        {
            return View();
        }
    }
}

Vidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content mt-4">
        @RenderBody()
        <hr/>
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

Vidly/Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    @Html.ActionLink("Vidly", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsable" aria-controls="collapsable" aria-expanded="false" aria-label="Toggle navigation" style="">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsable" style="">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">@Html.ActionLink("New Rental", "New", "Rentals", new { area = "" }, new { @class = "nav-link" })</li>
            <li class="nav-item">@Html.ActionLink("Customers", "Index", "Customers", new {area = ""}, new {@class = "nav-link"})</li>
            <li class="nav-item">@Html.ActionLink("Movies", "Index", "Movies", new {area = ""}, new {@class = "nav-link"})</li>
        </ul>
        @Html.Partial("_LoginPartial")

    </div>
</nav>